import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
const prisma = new PrismaClient();
const plans = [{ name: 'Fiber 25 Mbps', price: 599, speed: '25 Mbps' }, { name: 'Fiber 50 Mbps', price: 799, speed: '50 Mbps' }, { name: 'Fiber 100 Mbps', price: 999, speed: '100 Mbps' }];
async function main() {
  await prisma.message.deleteMany(); await prisma.notification.deleteMany(); await prisma.ticket.deleteMany(); await prisma.installation.deleteMany(); await prisma.bill.deleteMany(); await prisma.booking.deleteMany(); await prisma.subscriber.deleteMany(); await prisma.technician.deleteMany(); await prisma.user.deleteMany();
  const users = [{ id: 'USR-ADMIN', name: 'Sky-Tech Admin', email: 'admin@skytech.net', password: 'admin123', role: 'admin' as const }, { id: 'USR-TECH', name: 'Luis Dela Cruz', email: 'tech@skytech.net', password: 'tech123', role: 'technician' as const, technicianId: '100001' }, { id: 'USR-SUB', name: 'Alex Rivera', email: 'user1@skytech.net', password: 'user123', role: 'subscriber' as const, subscriberId: '100000001' }];
  for (const user of users) await prisma.user.create({ data: { id: user.id, name: user.name, email: user.email, password: await bcrypt.hash(user.password, 10), role: user.role, technicianId: user.technicianId, subscriberId: user.subscriberId } });
  await prisma.technician.createMany({ data: Array.from({ length: 5 }, (_, index) => ({ id: String(100001 + index), name: index === 0 ? 'Luis Dela Cruz' : `Technician ${index + 1}`, email: index === 0 ? 'tech@skytech.net' : `tech${index + 1}@skytech.net`, specialization: index % 2 ? 'Fiber Installation' : 'Network Repair', status: 'Active' as const })) });
  await prisma.subscriber.createMany({ data: Array.from({ length: 10 }, (_, index) => ({ id: String(100000001 + index), name: index === 0 ? 'Alex Rivera' : `Subscriber ${index + 1}`, email: index === 0 ? 'user1@skytech.net' : `user${index + 1}@example.com`, contact: '+63 917 555 0100', address: 'Makati City', plan: (index % 3 === 0 ? 'Fiber_25Mbps' : index % 3 === 1 ? 'Fiber_50Mbps' : 'Fiber_100Mbps') as 'Fiber_25Mbps' | 'Fiber_50Mbps' | 'Fiber_100Mbps', status: 'Active' as const, connectionDate: new Date() })) });
  const subscriber = await prisma.subscriber.findUniqueOrThrow({ where: { id: '100000001' } });
  await prisma.bill.createMany({ data: Array.from({ length: 10 }, (_, index) => ({ id: `BILL-${String(index + 1).padStart(3, '0')}`, subscriberId: subscriber.id, plan: subscriber.plan, billingPeriod: `2026-${String((index % 9) + 1).padStart(2, '0')}`, amount: plans[subscriber.plan === 'Fiber_25Mbps' ? 0 : subscriber.plan === 'Fiber_50Mbps' ? 1 : 2].price, dueDate: new Date(Date.now() + index * 86400000), status: index < 3 ? 'Paid' as const : index === 3 ? 'Overdue' as const : 'Unpaid' as const })) });
  await prisma.installation.createMany({ data: Array.from({ length: 9 }, (_, index) => ({ id: String(1000001 + index), subscriberId: subscriber.id, technicianId: '100001', address: subscriber.address, date: new Date(Date.now() + index * 86400000), time: '10:00 AM', type: index % 3 === 0 ? 'Installation' as const : 'Maintenance' as const, status: index < 2 ? 'Completed' as const : 'Scheduled' as const })) });
  await prisma.booking.createMany({ data: Array.from({ length: 3 }, (_, index) => ({ id: `BOOK-${index + 1}`, name: `Booking Guest ${index + 1}`, contact: '+63 917 111 0000', email: `guest${index + 1}@example.com`, address: 'Quezon City', plan: 'Fiber_50Mbps' as const, preferredDate: new Date(Date.now() + index * 86400000), status: 'Pending' as const })) });
  await prisma.ticket.createMany({ data: Array.from({ length: 5 }, (_, index) => ({ id: String(10000001 + index), subscriberId: subscriber.id, type: index % 2 ? 'Slow_Internet_Connection' as const : 'No_Internet_Connection' as const, subject: 'Connection support request', description: 'Please help check my connection.', status: index === 0 ? 'Open' as const : 'In_Progress' as const, priority: index === 0 ? 'High' as const : 'Medium' as const })) });
  await prisma.notification.createMany({ data: [
    { forRole: 'subscriber' as const, forUserId: subscriber.id, type: 'billing' as const, title: 'Bill Generated', body: 'Your June 2026 bill is ready: ₱999.00. Due on June 30, 2026.', timestamp: new Date('2026-06-01T08:00:00Z'), read: false },
    { forRole: 'subscriber' as const, forUserId: subscriber.id, type: 'billing' as const, title: 'Payment Confirmed', body: 'Your May 2026 payment of ₱999.00 has been received. Thank you!', timestamp: new Date('2026-05-28T08:00:00Z'), read: true },
    { forRole: 'subscriber' as const, forUserId: subscriber.id, type: 'installation' as const, title: 'Installation Scheduled', body: 'Technician Marcus Chen will visit on June 13 at 09:00 for fiber installation.', timestamp: new Date('2026-06-10T08:00:00Z'), read: true },
    { forRole: 'subscriber' as const, forUserId: subscriber.id, type: 'task' as const, title: 'Repair Scheduled', body: 'Technician Marcus Chen will visit on June 18 at 13:00 for your repair request.', timestamp: new Date('2026-06-15T08:00:00Z'), read: true },
  ] });
  await prisma.notification.createMany({ data: Array.from({ length: 12 }, (_, index) => ({ forRole: index % 3 === 0 ? 'admin' as const : index % 3 === 1 ? 'technician' as const : 'subscriber' as const, type: 'system' as const, title: 'Sky-Tech update', body: 'Your account has a new service update.' })) });
  await prisma.systemSettings.create({ data: { companyName: 'Sky-Tech ISP', companyEmail: 'support@skytech.net', phone: '+63 900 000 0000', address: 'Metro Manila', lateFeePercent: 5, gracePeriodDays: 5, billingDay: 30, plans } });
}
main().finally(() => prisma.$disconnect());
